### ISSUE TITLE
Display Z information from polyline as elevation

### ISSUE THREAD

**Issue by jamaa** [PANOimagen/profiletool#101]
I have 3D polylines (MultiLineStringZ) representing cross-sections with elevation information stored as the Z property of each vertex and would like to have that information displayed alongside the elevation of a raster or mesh datasource in the graph. I can select individual polylines to display elevation of a raster or mesh along that line, but the elevation of the line itself is not displayed. Is it possible? Am I missing something or is this something that would have to programmed?

**Comment by nicogodet** [comment]
Hi,

Please see this comment https://github.com/PANOimagen/profiletool/issues/96#issuecomment-1893128810

**Comment by jamaa** [comment]
Thanks for the quick reply! I never knew about this builtin elevation profile feature. I guess that makes the Profile Tool plugin a little obsolete now, but thanks for your past work on it!
