### ISSUE TITLE
Issue with calculating slope

### ISSUE THREAD

**Issue by conorferguson** [PANOimagen/profiletool#11]
Hello,

I'm new to Github so forgive my ignorance... i assume this is the channel for raising queries and questions. 

I'm having an issue with calculating the slope in degrees using your tool. I input the DEM and a vector line and the profile shown seems to be correct... the x value displays the correct horizontal distance in meters and the y value displays the correct vertical distance in meters.

However, when I select slope (degrees) the values are not correct. I know this because I have calculated what the correct values should be using the x and y values (rise over run). I can only think that I am making a simple mistake but I cannot find any instructions or helpfile with how to use your tool correctly.

I suspect that it has something to do with the CRS (projection). My DEM and vector line are using a datum in Taiwan (3826).

Are there helpfiles or instructions online?
Do i also have to set the vertical datum somehow?

**Comment by JaviBecerra** [comment]
Hi @conorferguson,
Welcome to GitHub! Yes, this is the proper way to address this kind of issues.
We will double check the slope calculation. However, if you can provide us with a sample dem+polyline to reproduce your issue it will make it easier for us to identify the problem.

**Comment by conorferguson** [comment]
Hello Javi,

My apologies, upon further analysis I have determined that I was the one making a mistake. I believe now that your slope calculation tool works fine. It has actually highlighted some high slope areas in our survey that previously we believed were fine.

To summarise, I retract the issue... slope tool is ok!

**Comment by JaviBecerra** [comment]
Thanks @conorferguson for taking the time to report and coming back to close the issue.
Glad to hear that the slope feature has been useful!
Regards
