### ISSUE TITLE
Add option to export 2D profile as dxf

### ISSUE THREAD

**Issue by JaviBecerra** [PANOimagen/profiletool#16]
_Originally posted by @marcodallago in https://github.com/PANOimagen/profiletool/issues/15#issuecomment-460236038_

**Comment by JaviBecerra** [comment]
Hi @marcodallago,
Can you check if commit https://github.com/PANOimagen/profiletool/commit/539cd056099cbe34b87351e7eca3fef97aa082af new option to export 2D profiles as dfx works fine?
Regards

**Comment by marcodallago** [comment]
@JaviBecerra works great thanks!!

Just wondering, with 2d output there is one information lacking, which is ground ( 0 height ). Could you please add in the 2d dxf output a ground line representing 0 height? Do you find it useful?

**Comment by JaviBecerra** [comment]
Hi @marcodallago,
Glad it is working fine.
From our point of view, the rationale with exporting the 2D profile in dxf is so that it keeps the proper scale in meters; if you need a 0 axis you know it is placed at y value 0, anyone can add it if they wish.
If all you need is a graph with axes and you do not care about the scale then you would choose a png or svg export that (I'm assuming here, I'm not really a CAD user) you can later embed in your cad file, independent of the graph scale (as it has its own x and y axis).
We are closing the issue now, feel free to open a new one if you really feel that exporting the graph with axis in dxf format would really add value to ProfileTool so that we can get some additional feedback, but I doubt it is something we will be prioritizing at the moment.
Regards
