### ISSUE TITLE
Qgis crash when adding a point shape

### ISSUE THREAD

**Issue by nicogodet** [PANOimagen/profiletool#20]
Profile tool version : 4.1.5
Qgis version : 2.18.17 & 2.18.28

As mentionned in the title, when I add a point shape layer, it results in a crash of Qgis on both versions.
The crash appears after I've chosen the field.

No issue with raster

**Comment by JaviBecerra** [comment]
Hi @nicogodet,
We are checking the issue, we have reproduced it on QGis 2 but it is working properly on QGis 3.
If I may ask, is there any reason that keeps you from updating to QGis 3.4 (latest LTR available)?

**Comment by nicogodet** [comment]
Hi @JaviBecerra, 
My whole compagny is working on Qgis 2 and we developped plugins for Qgis 2 that are not updated for Qgis 3 yet...
