### ISSUE TITLE
"Cursor" is visible in saved png.

### ISSUE THREAD

**Issue by JaviBecerra** [PANOimagen/profiletool#21]
The cursor in the graph window is saved in the png, it would be great if it it wasnt.
(Initially reported by @APOS80 at etiennesky/profiletool#61).

**Comment by JaviBecerra** [comment]
Hi @APOS80,
Cursor should not appear on the exported graph if you uncheck the 'Show cursor' checkbox (should be on the right of the 'save as' button).
If it continues showing after you uncheck this option, then this is a bug.

**Comment by APOS80** [comment]
Sorry, missed that.
