### ISSUE TITLE
Profile Table data collapsed

### ISSUE THREAD

**Issue by serialc** [PANOimagen/profiletool#25]
Hi,

A great plugin, thanks.

In QGIS 3.6.2 on Ubuntu 19.4:
After having successfully created a profile, when I look to export the data in the Table tab I get a compressed layout. The table is collapsed - only 1-2 pixel height and the buttons, below the table, have no padding. This isn't for lack of data - the copied data is over a thousand lines.

See below:
![Screenshot from 2019-05-09 20-19-51](https://user-images.githubusercontent.com/777410/57480998-0e7ac380-7299-11e9-8575-8728a4575148.png)

The profile shows up fine.
![Screenshot from 2019-05-09 20-32-30](https://user-images.githubusercontent.com/777410/57481283-ac6e8e00-7299-11e9-9ead-18590737b47e.png)

I'll see if I can solve it on my end...

Thanks,
Cyrille

**Comment by JaviBecerra** [comment]
Hi @serialc,
Thanks for the feedback. 
The widgets on the table view were set to fixed sizes and that was causing problems when using bigger than usual system font sizes (at least usual with smaller resolution - i.e. full HD- displays).
I have uploaded a couple commits to fix this, please check that it is working fine for you now.
Regards

**Comment by serialc** [comment]
That fixed it - thanks!

![Screenshot from 2019-05-10 20-26-07](https://user-images.githubusercontent.com/777410/57551862-06d32180-7362-11e9-80d7-d78a542c9d85.png)
