### ISSUE TITLE
Exporting to Matplotlib

### ISSUE THREAD

**Issue by codeyfodey** [PANOimagen/profiletool#30]
Hello, I have encountered an issue when attempting to export my profile to Matplotlib. 

It appears that the plugin still uses the .iteritems( ) on the dictionary object. Will this need updating to .items( ) as QGIS 3 now runs in Python3?

I attempted to manually change the 'Matplotlib.py' exporter script, but I was still met with the same issue. Your help would be much appreciated.

<img width="505" alt="profile_tool_error" src="https://user-images.githubusercontent.com/52499583/60603996-af27c400-9dae-11e9-8e02-8ef6b71582c1.PNG">

Let me know if you need any further details.

**Comment by JaviBecerra** [comment]
Hi @codeyfodey:
Thanks for reporting!
That is an issue with the bundled pyqtgraph library (see https://github.com/pyqtgraph/pyqtgraph/pull/690).
We have made a couple commits (a6e066fb04 and 3e0dc40ed) to update the library on the repo using pyqtgraphs latest fixes, this should get it working.
Please install the plugin using the latest commits in this repository to check that the solution is working for you and we will update the plugin on QGIS repositories.
Regards

**Comment by codeyfodey** [comment]
Javi thanks for enacting this update. I have tested the plugin with the latest commits and it now exports without issue.  

Regards

Adam
