### ISSUE TITLE
QGIS crash when closing the panel after layer deletion

### ISSUE THREAD

**Issue by jeremyk6** [PANOimagen/profiletool#32]
ProfileTool 4.1.7
QGIS dev and QGIS 3.8

After plotting a dem, if the dem is deleted from QGIS and the ProfileTool panel is closed without removing the dem plotted from it, QGIS crash. Tested on several rasters with the same effect.

**Comment by jeremyk6** [comment]
It seems the layer, after removal, is still in the dockwidget model : crash on profiletool_core.py:176.
As a workaround, I added layer1.willBeDeleted.connect(self.removeLayer) in ptdockwidget.py:337 to force the layer deletion from dock.

**Comment by JaviBecerra** [comment]
Hi @jeremyk6,
Thanks for reporting and proposing a fix!
Let me take a look at this and I will update the repo.
Regards

**Comment by nicogodet** [comment]
Hi,
Nearly one year since this issue is opened and a fix is proposed...
Still not fixed
