### ISSUE TITLE
Layout profile too version 4.1.7

### ISSUE THREAD

**Issue by samillesouza** [PANOimagen/profiletool#36]
Hello,
I used profile too version 4.1.7, with Matplotlib plot library in qgis3.4.5, when selecting the vector with selected polyline the layout brings black lines that cut the profile, even more, when setting the minimum and maximum the layout shows the lines black only halfway through the layout. How to remove these black lines? Follows prints with the obtained results.
![Test1](https://user-images.githubusercontent.com/55593707/66954826-86fb6280-f037-11e9-88e7-abac5103ea13.JPG)
![Test2](https://user-images.githubusercontent.com/55593707/66954828-86fb6280-f037-11e9-9a06-c6f8a6d859b2.JPG)

**Comment by JaviBecerra** [comment]
Hi @samillesouza,

Can you provide a sample dataset so that we can reproduce this?
Thanks

**Comment by samillesouza** [comment]
Hello, attached is the shape with the selected line for the extraction of the profile and raster mosaic.
[Shape.zip](https://github.com/PANOimagen/profiletool/files/3739062/Shape.zip)

**Comment by samillesouza** [comment]
Hello, attached is the shape with the selected line for profile extraction, the raster mosaic has more than 10MB and so I could not upload. It can be found at the link: http://www.dsr.inpe.br/topodata/data/geotiff/12S405ZN.zip

[Shape.zip](https://github.com/PANOimagen/profiletool/files/3739146/Shape.zip)

**Comment by samillesouza** [comment]
Hello, could you identify the problem? Awaiting! Thank you!
