### ISSUE TITLE
Profile Select Polyline Crashes Project: QGIS 3.10 & QGIS 3.12

### ISSUE THREAD

**Issue by RichardClutterbuck** [PANOimagen/profiletool#39]
I'm afraid the Profile Tool's 'Select polyline' results in both QGIS 3.10 and QGIS 3.12 crashing. The Temporary polyline function works. This still works on QGIS 3.4.

I'm using QGIS on a Windows 64 bit operating system;  Windows 10 Home, with an Intel(R) Core i7 CPU, 16 GB of RAM.

**Comment by JaviBecerra** [comment]
Closing this as duplicate of issue #35
