### ISSUE TITLE
Profile tool not available to install from QGIS plugin manager (QGIS 3.12 on Mac)

### ISSUE THREAD

**Issue by RobertoPanoi** [PANOimagen/profiletool#43]
A user has reported that the "Profile tool" plugin does not appear to install from the QGIS plugin manager (QGIS 3.12 on Mac)
<img width="1187" alt="Screenshot 2020-05-14 at 14 37 19" src="https://user-images.githubusercontent.com/31844800/82027364-6ca06a80-9694-11ea-9dd7-a79552627744.png">

On Windows it appears to be installed from the QGIS plugin manager (QGIS 3.12 on Windows)
![Proyecto sin título - QGIS 14_05_2020 18_53_24](https://user-images.githubusercontent.com/31844800/82027446-8fcb1a00-9694-11ea-92d9-305985d88d89.png)

The plugin is not experimental

**Comment by Sinan81** [comment]
I'm told by a user that profiletool also seem to be not available for QGIS@2.18 (built from source under centos 7.6)

**Comment by nicogodet** [comment]
@RobertoPanoi Fixed ?
(But I think I can't do anything from here.)
