### ISSUE TITLE
Selected Polyline Profile

### ISSUE THREAD

**Issue by gasiva** [PANOimagen/profiletool#56]
Creating a profile from "selected polyline" doesn't work while "selected layer" option has no preoblem.
Does anyone experience the same problem?

**Comment by nicogodet** [comment]
1. Select "Selected polyline"
2. Select a polyline layer in Qgis Tree
3. Click on polyline in Qgis canvas

![profiletool](https://user-images.githubusercontent.com/39594821/110797952-f5b70c80-8279-11eb-8696-d0ee3be53a3f.gif)

This doesn't work ?

**Comment by JaviBecerra** [comment]
Hi @gasiva:
Not sure if this is related, but can you check your layer type? 
We have yet to find out whe, but is seems that Multipoint geometries are not working with the plugin right now, while Point geometries work fine, maybe that is the issue you are facing?

Regards,
Javier

**Comment by gasiva** [comment]
@nicogodet thank you! It works. I was selecting the polyline with the selection tool :(

**Comment by nicogodet** [comment]
@gasiva if your problem is solved, you can close this issue ;)
