### ISSUE TITLE
Profile line not visible if portion does not have DEM

### ISSUE THREAD

**Issue by kobusburger** [PANOimagen/profiletool#59]
The profile line is not visible when the polyline or layer covers an area that is not covered by the DEM. Included are images where the profile line is visible and not visible. Note that the elevation information does show but not the line. The table does show data for the portion that is covered by the DEM.
![image](https://user-images.githubusercontent.com/6264060/124381228-92863580-dcc1-11eb-9a44-e254c2ea0167.png)
![image](https://user-images.githubusercontent.com/6264060/124381250-bfd2e380-dcc1-11eb-8a62-4cd996f8e6f3.png)
![image](https://user-images.githubusercontent.com/6264060/124381348-4c7da180-dcc2-11eb-937a-2f3b0c577b5d.png)
![image](https://user-images.githubusercontent.com/6264060/124381307-0f191400-dcc2-11eb-936a-4d5f40f3237c.png)

**Comment by nicogodet** [comment]
I believe you have this issue on a qgis install with Numpy 1.20 ? Like OsGeo4W v2 ?

I fixed this issue on a local repo, I will submit a PR.

**Comment by kobusburger** [comment]
I am using QGIS 3.20.0


QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909




Active Python plugins
kmltools
profiletool
db_manager
MetaSearch
processing

**Comment by nicogodet** [comment]
@kobusburger 
Try this : [profiletool.zip](https://github.com/PANOimagen/profiletool/files/6762156/profiletool.zip)
It comes from https://github.com/nicogodet/profiletool/tree/dev

**Comment by kobusburger** [comment]
Thank you very much for the fast response and fix. The version you attached shows the profile lines even if a portion is not on the DEM.
