### ISSUE TITLE
QGIS 3.20 crashes on MAC (MacOS 13.1.2) 

### ISSUE THREAD

**Issue by tobat7** [PANOimagen/profiletool#64]
It just crashes QGIS (3.2.0) when I click on ProfileLine Tool icon. Tried to reinstall a few times.
MAC Version (high Sierra installed)

**Comment by nicogodet** [comment]
Could you be more specific ?
An error message for example ?

**Comment by tobat7** [comment]
Hi Nico, I'm not getting any error: I installed the plugin and everything went well. When I try to use the tool, just clicking on the icon, QGIS shuts down and I need to reopen it.

**Comment by tobat7** [comment]
I uninstallef QGIS 3.2.0 and installed 3.1.6 and it works just fine.

**Comment by nicogodet** [comment]
QGIS 3.2.0 ?
It's way too hold (or do you mean qgis 3.20 ?)

Which version of profiletool ?

Unfortunately, I don't have a Mac to replicate the issue...

**Comment by tobat7** [comment]
I am sorry, you are right, I meant QGIS 3**.20** (and 3.16 is where it works now)
I tried both 4.2.0 and 4.2.1 version of profiletool (installed within QGIS at first, then also with the .zip file)

**Comment by nicogodet** [comment]
Does it work on Qgis 3.20.x with a previous version of profiletool (Like 4.1.8) ?

**Comment by tobat7** [comment]
No it's not. Same crashing. 
Now I'm using it on QGIS 3.16. I'll upgrade at some point to 3.20 again and will try again, maybe the next release of Profiletool

**Comment by nicogodet** [comment]
For a next release of profiletool, I need to know why it crashes with MacOS.

I saw that QGIS for Mac will receive a major dependencies upgrade with 3.22. Maybe it will fix the issue.

Without a stack trace or error message, I can't do anything for now.

**Comment by tobat7** [comment]
I see. Unfortunately I can't help you with any error, it simply shuts down.
