### ISSUE TITLE
plugin Profile tool

### ISSUE THREAD

**Issue by diunida** [PANOimagen/profiletool#69]
The plugin incorrectly generates a terrain profile at a layer with several polylines if they are not inserted into the base in the correct order.
Trying to sort by changing the id of individual polylines fails.
Only copying the data (in the right order) to a spreadsheet and importing it as a "csv" file gives the desired effect.
Is this behavior intentional in that it only retrieves data from the database in the order in which it was first, without sorting?

**Comment by nicogodet** [comment]
Duplicates #60

The plugin can't guess the feature order you want. It just take feature in order they were created/inserted in the layer/database.
