### ISSUE TITLE
Bug scrolling in the profile in QGIS 3.30.2

### ISSUE THREAD

**Issue by cesarcorreo** [PANOimagen/profiletool#89]
After update to QGIS 3.30.2 it is not possible to scroll through the profile when the centre wheel is pressed.
I have tried this same QGIS (3.30.2) version with a new profile and it doesn't work either. 
In previous QGIS versions it works correctly.
Thanks

**Comment by nicogodet** [comment]
Upgrading pyqtgraph seems to solve the issue
But I'm not very confident that it does not break other things...

Could you try [profiletool.zip](https://github.com/PANOimagen/profiletool/files/11460511/profiletool.zip) and report if something fails ?

**Comment by nicogodet** [comment]
> Do you plan to update the plugin?

I count on you to use it for few days and report any behavior that would be broken
Then I will update
