### ISSUE TITLE
Failure to draw a temporary profile polyline after changing a tool.

### ISSUE THREAD

**Issue by MrChebur** [PANOimagen/profiletool#96]
While working with the plugin, if you change the tool to a different tool, it becomes unclear to the user how to go back to the tool that draws temporary polylines. 

It turns out that to start drawing profile lines again it is necessary to press the button that starts the plugin in the plugin menu.

![изображение](https://github.com/PANOimagen/profiletool/assets/20655102/af5446f2-6aa6-4313-a5f4-d4d15799ac43)

This is a strong omission in the plugin interface. 

To fix it, I suggest adding the corresponding button "draw temporary polyline" to the plugin window.

![изображение](https://github.com/PANOimagen/profiletool/assets/20655102/9e4f4742-191b-40d3-8136-b881a398c49c)

**Comment by nicogodet** [comment]
Feel free to create a MR that implement that.

As QGIS have a profile tool in core now, I will only work on bug that make this plugin unusable.

**Comment by MrChebur** [comment]
Oh, I didn't know about that!
https://docs.qgis.org/3.28/en/docs/user_manual/map_views/elevation_profile.html
