### ISSUE TITLE
[Feature requests] Interface Improvement.

### ISSUE THREAD

**Issue by MrChebur** [PANOimagen/profiletool#97]
Your plugin is very good. Thank you for supporting its development.
Here are some comments on the plugin interface that would improve user experience:

1. Add raster layers by "drag and drop".
2. Allow layers to be repositioned after they are added.
3. Remove layers from the table in a more user-friendly way:
-- select layers in the table
-- click the delete layers button
-- confirm deletion (or cancel it) in the new window

**Comment by nicogodet** [comment]
See https://github.com/PANOimagen/profiletool/issues/96#issuecomment-1893128810

**Comment by nicogodet** [comment]
Ideally, you should split this feature request in 3 for each point you ask for

**Comment by MrChebur** [comment]
Oh, I didn't know about core elevation profile tool!
https://docs.qgis.org/3.28/en/docs/user_manual/map_views/elevation_profile.html
